version: '3.9'
services:
  web:
    build: .
    ports:
      - "8080:80"
    # Uncomment to live-rebuild inside container (heavier). For now, we build during image build.
    # volumes:
    #   - .:/app
    # command: sh -c "bun run build && nginx -g 'daemon off;'"

